### PR TITLE
fixed #744

### LINKED ISSUE #744: Pagination on MMItem - List not working
MM: dev-tng (ab17f59)

Cause of the last commit where the Pagination was moved to an explicit helper file the pagination is not working anymore

### PR DESCRIPTION
**Pull request by MrTool**
you forgot to set the current page attribute depending on the page parameter if set and integer

### CODE REVIEW

File: src/MetaModels/ItemList.php [hunk 1]
```diff
@@ -575,6 +575,10 @@ public function prepare()
 
         $calculator = $this->paginationLimitCalculator;
         $calculator->setTotalAmount($intTotal);
+        $curPage = (int) \Input::get('page');
+        if(is_int($curPage) && $curPage > 1){
```
Comment (discordier) [inline src/MetaModels/ItemList.php]: This check is obsolete as you are casting to int here. Therefore the condition is always true.

**Comment by Zeromax** [comment]
This fix works ;) Please merge it.
